username = input("Введите имя пользователя: ")
title1 = input("Введите заголовок заметки:  ")
title2 = input("Введите заголовок заметки:  ")
title3 = input("Введите заголовок заметки:  ")
titles = [title1, title2, title3]
content = input("Введите описание заметки: ")
status = input("Введите статус заметки: ")
created_date = input('Введите дату создания заметки в формате "день-месяц-год": ')
issue_date = input('Введите дату истечения заметки в формате "день-месяц-год" : ')
print("Имя пользователя : ", username)
print("Заголовок заметки : ", titles)
print("Описание заметки : ", content)
print("Статус заметки : ", status)
print('Дата создания заметки: ', created_date[:5])
print('Дата истечения заметки: ', issue_date[:5])